import argparse
import sys

ratio = None
countries_cases_stats = {'North America': [1120629, 176247],
                         'Europe': [1322784, 459814],
                         'Asia': [495132, 246272],
                         'South America': [155592, 54294],
                         'Oceania': [8314, 6933],
                         'Africa': [35779, 11868],
                         'World': [3138951, 956073],
                         'USA': [1035765, 142238],
                         'Spain': [232128, 123903],
                         'Italy': [201505, 68941],
                         'France': [165911, 46886],
                         'UK': [161145, 0],
                         'Germany': [159912, 117400],
                         'Turkey': [114653, 38809],
                         'Russia': [93558, 8456],
                         'Iran': [92584, 72439],
                         'Brazil': [73235, 32544],
                         'Canada': [50026, 19190],
                         'Belgium': [47334, 10943],
                         'Netherlands': [38416, 0],
                         'India': [31332, 7747],
                         'Peru': [31190, 9179],
                         'Switzerland': [29264, 22600],
                         'Portugal': [24322, 1389],
                         'Ecuador': [24258, 1557],
                         'Saudi Arabia': [20077, 2784],
                         'Ireland': [19877, 9233],
                         'Sweden': [19621, 1005],
                         'Mexico': [16752, 11423],
                         'Israel': [15728, 7746],
                         'Austria': [15357, 12580],
                         'Singapore': [14951, 1128],
                         'Pakistan': [14885, 3425],
                         'Chile': [14365, 7710],
                         'Japan': [13736, 1899],
                         'Poland': [12218, 2655],
                         'Belarus': [12208, 1993],
                         'Qatar': [11921, 1134],
                         'Romania': [11616, 3404],
                         'UAE': [11380, 2181],
                         'S. Korea': [10761, 8922],
                         'Indonesia': [9511, 1254],
                         'Ukraine': [9410, 992],
                         'Denmark': [8851, 6121],
                         'Serbia': [8497, 1260],
                         'Philippines': [7958, 975],
                         'Norway': [7660, 32],
                         'Czechia': [7504, 2948],
                         'Australia': [6738, 5626],
                         'Bangladesh': [6462, 139],
                         'Dominican Republic': [6416, 1165],
                         'Panama': [6200, 484],
                         'Colombia': [5949, 1268],
                         'Malaysia': [5851, 4032],
                         'Egypt': [5042, 1304],
                         'South Africa': [4996, 2073],
                         'Finland': [4740, 2800],
                         'Morocco': [4252, 778],
                         'Argentina': [4127, 1162],
                         'Luxembourg': [3741, 3123],
                         'Algeria': [3649, 1651],
                         'Moldova': [3638, 975],
                         'Kuwait': [3440, 1176],
                         'Kazakhstan': [3027, 774],
                         'Thailand': [2947, 2665],
                         'Bahrain': [2811, 1310],
                         'Hungary': [2727, 536],
                         'Greece': [2566, 577],
                         'Oman': [2131, 364],
                         'Croatia': [2047, 1232],
                         'Uzbekistan': [1955, 992],
                         'Iraq': [1928, 1319],
                         'Armenia': [1867, 866],
                         'Afghanistan': [1828, 228],
                         'Cameroon': [1806, 915],
                         'Iceland': [1795, 1636],
                         'Azerbaijan': [1717, 1221],
                         'Ghana': [1671, 188],
                         'Estonia': [1660, 240],
                         'Bosnia and Herzegovina': [1585, 682],
                         'Nigeria': [1532, 255],
                         'New Zealand': [1474, 1229],
                         'Cuba': [1437, 575],
                         'North Macedonia': [1421, 589],
                         'Slovenia': [1408, 223],
                         'Bulgaria': [1399, 222],
                         'Slovakia': [1384, 423],
                         'Lithuania': [1344, 536],
                         'Guinea': [1240, 269],
                         'Ivory Coast': [1183, 525],
                         'Djibouti': [1072, 498],
                         'Bolivia': [1053, 110],
                         'Hong Kong': [1038, 811],
                         'Tunisia': [975, 279],
                         'Cyprus': [837, 148],
                         'Latvia': [836, 267],
                         'Senegal': [823, 296],
                         'Albania': [750, 431],
                         'Andorra': [743, 398],
                         'Honduras': [738, 73],
                         'Kyrgyzstan': [729, 437],
                         'Lebanon': [717, 145],
                         'Diamond Princess': [712, 645],
                         'Niger': [709, 403],
                         'Costa Rica': [705, 306],
                         'Burkina Faso': [638, 476],
                         'Uruguay': [625, 394],
                         'Sri Lanka': [619, 134],
                         'Guatemala': [577, 62],
                         'San Marino': [553, 64],
                         'Channel Islands': [530, 352],
                         'Somalia': [528, 19],
                         'Georgia': [511, 168],
                         'DRC': [471, 56],
                         'Mayotte': [460, 235],
                         'Malta': [458, 303],
                         'Jordan': [449, 348],
                         'Taiwan': [429, 307],
                         'Mali': [424, 122],
                         'RÃ©union': [418, 300],
                         'Jamaica': [381, 29],
                         'El Salvador': [377, 106],
                         'Kenya': [374, 124],
                         'Palestine': [343, 71],
                         'Mauritius': [334, 303],
                         'Venezuela': [329, 142],
                         'Montenegro': [321, 199],
                         'Sudan': [318, 31],
                         'Equatorial Guinea': [315, 9],
                         'Isle of Man': [309, 252],
                         'Tanzania': [299, 48],
                         'Vietnam': [270, 222],
                         'Maldives': [250, 17],
                         'Paraguay': [239, 102],
                         'Gabon': [238, 53],
                         'Rwanda': [212, 95],
                         'Congo': [207, 19],
                         'Faeroe Islands': [187, 181],
                         'Martinique': [175, 83],
                         'Myanmar': [150, 16],
                         'Guadeloupe': [149, 82],
                         'Liberia': [141, 45],
                         'Gibraltar': [141, 131],
                         'Brunei': [138, 124],
                         'Madagascar': [128, 82],
                         'Ethiopia': [126, 50],
                         'French Guiana': [125, 93],
                         'Cambodia': [122, 119],
                         'Trinidad and Tobago': [116, 59],
                         'Cabo Verde': [114, 2],
                         'Bermuda': [110, 44],
                         'Sierra Leone': [104, 12],
                         'Aruba': [100, 73],
                         'Togo': [99, 63],
                         'Monaco': [95, 50],
                         'Zambia': [95, 32],
                         'Liechtenstein': [82, 55],
                         'Bahamas': [80, 23],
                         'Barbados': [80, 39],
                         'Uganda': [79, 52],
                         'Haiti': [76, 8],
                         'Mozambique': [76, 12],
                         'Sint Maarten': [75, 33],
                         'Guyana': [74, 15],
                         'Guinea-Bissau': [73, 18],
                         'Eswatini': [71, 10],
                         'Cayman Islands': [70, 10],
                         'Benin': [64, 33],
                         'Libya': [61, 18],
                         'French Polynesia': [58, 49],
                         'Nepal': [54, 16],
                         'Chad': [52, 19],
                         'CAR': [50, 10],
                         'Macao': [45, 32],
                         'Syria': [43, 21],
                         'Eritrea': [39, 19],
                         'Saint Martin': [38, 24],
                         'Mongolia': [38, 10],
                         'Malawi': [36, 5],
                         'South Sudan': [34, 1],
                         'Zimbabwe': [32, 5],
                         'Angola': [27, 6],
                         'Antigua and Barbuda': [24, 11],
                         'Timor-Leste': [24, 6],
                         'Botswana': [23, 1],
                         'Grenada': [19, 10],
                         'Laos': [19, 7],
                         'Belize': [18, 9],
                         'Fiji': [18, 12],
                         'New Caledonia': [18, 17],
                         'CuraÃ§ao': [16, 11],
                         'Dominica': [16, 13],
                         'Namibia': [16, 8],
                         'Saint Kitts and Nevis': [15, 4],
                         'Saint Lucia': [15, 15],
                         'St. Vincent Grenadines': [15, 8],
                         'Nicaragua': [19, 7],
                         'Falkland Islands': [13, 11],
                         'Turks and Caicos': [12, 5],
                         'Burundi': [11, 4],
                         'Montserrat': [11, 2],
                         'Greenland': [11, 11],
                         'Seychelles': [11, 6],
                         'Gambia': [10, 8],
                         'Suriname': [10, 7],
                         'Vatican City': [10, 2],
                         'MS Zaandam': [9, 1],
                         'Papua New Guinea': [8, 1],
                         'Sao Tome and Principe': [8, 4],
                         'Mauritania': [7, 6],
                         'Bhutan': [7, 5],
                         'British Virgin Islands': [6, 3],
                         'St. Barth': [6, 6],
                         'Western Sahara': [6, 5],
                         'Caribbean Netherlands': [5, 1],
                         'Anguilla': [3, 3],
                         'Saint Pierre Miquelon': [1, 1],
                         'Yemen': [1, 1],
                         'China': [82858, 77578],
                         }


def total_recovered_ratio(country):
    global ratio
    my_list = countries_cases_stats[country]

    try:
        ratio = my_list[1] / my_list[0]

    except ZeroDivisionError:
        print("Can't divide by zero!")
        sys.exit(1)

    return f'Recovered/total ratio: {ratio}'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('country_name', help='Enter Country Name In Capwords',
                        choices=['North America', 'Europe', 'Asia',
                                 'South America', 'Oceania', 'Africa',
                                 'World', 'USA', 'Spain',
                                 'Italy', 'France', 'UK',
                                 'Germany', 'Turkey', 'Russia',
                                 'Iran', 'Brazil', 'Canada',
                                 'Belgium', 'Netherlands', 'India',
                                 'Peru', 'Switzerland', 'Portugal',
                                 'Ecuador', 'Saudi Arabia', 'Ireland',
                                 'Sweden', 'Mexico', 'Israel',
                                 'Austria', 'Singapore', 'Pakistan',
                                 'Chile', 'Japan', 'Poland',
                                 'Belarus', 'Qatar', 'Romania',
                                 'UAE', 'S. Korea', 'Indonesia',
                                 'Ukraine', 'Denmark', 'Serbia',
                                 'Philippines', 'Norway', 'Czechia',
                                 'Australia', 'Bangladesh', 'Dominican Republic',
                                 'Panama', 'Colombia', 'Malaysia',
                                 'Egypt', 'South Africa', 'Finland',
                                 'Morocco', 'Argentina', 'Luxembourg',
                                 'Algeria', 'Moldova', 'Kuwait',
                                 'Kazakhstan', 'Thailand', 'Bahrain',
                                 'Hungary', 'Greece', 'Oman',
                                 'Croatia', 'Uzbekistan', 'Iraq',
                                 'Armenia', 'Afghanistan', 'Cameroon',
                                 'Iceland', 'Azerbaijan', 'Ghana',
                                 'Estonia', 'Bosnia and Herzegovina', 'Nigeria',
                                 'New Zealand', 'Cuba', 'North Macedonia',
                                 'Slovenia', 'Bulgaria', 'Slovakia',
                                 'Lithuania', 'Guinea', 'Ivory Coast',
                                 'Djibouti', 'Bolivia', 'Hong Kong',
                                 'Tunisia', 'Cyprus', 'Latvia',
                                 'Senegal', 'Albania', 'Andorra',
                                 'Honduras', 'Kyrgyzstan', 'Lebanon',
                                 'Diamond Princess', 'Niger', 'Costa Rica',
                                 'Burkina Faso', 'Uruguay', 'Sri Lanka',
                                 'Guatemala', 'San Marino', 'Channel Islands',
                                 'Somalia', 'Georgia', 'DRC',
                                 'Mayotte', 'Malta', 'Jordan',
                                 'Taiwan', 'Mali', 'RÃ©union',
                                 'Jamaica', 'El Salvador', 'Kenya',
                                 'Palestine', 'Mauritius', 'Venezuela',
                                 'Montenegro', 'Sudan', 'Equatorial Guinea',
                                 'Isle of Man', 'Tanzania', 'Vietnam',
                                 'Maldives', 'Paraguay', 'Gabon',
                                 'Rwanda', 'Congo', 'Faeroe Islands',
                                 'Martinique', 'Myanmar', 'Guadeloupe',
                                 'Liberia', 'Gibraltar', 'Brunei',
                                 'Madagascar', 'Ethiopia', 'French Guiana',
                                 'Cambodia', 'Trinidad and Tobago', 'Cabo Verde',
                                 'Bermuda', 'Sierra Leone', 'Aruba',
                                 'Togo', 'Monaco', 'Zambia',
                                 'Liechtenstein', 'Bahamas', 'Barbados',
                                 'Uganda', 'Haiti', 'Mozambique',
                                 'Sint Maarten', 'Guyana', 'Guinea-Bissau',
                                 'Eswatini', 'Cayman Islands', 'Benin',
                                 'Libya', 'French Polynesia', 'Nepal',
                                 'Chad', 'CAR', 'Macao',
                                 'Syria', 'Eritrea', 'Saint Martin',
                                 'Mongolia', 'Malawi', 'South Sudan',
                                 'Zimbabwe', 'Angola', 'Antigua and Barbuda',
                                 'Timor-Leste', 'Botswana', 'Grenada',
                                 'Laos', 'Belize', 'Fiji',
                                 'New Caledonia', 'CuraÃ§ao', 'Dominica',
                                 'Namibia', 'Saint Kitts and Nevis', 'Saint Lucia',
                                 'St. Vincent Grenadines', 'Nicaragua', 'Falkland Islands',
                                 'Turks and Caicos', 'Burundi', 'Montserrat',
                                 'Greenland', 'Seychelles', 'Gambia',
                                 'Suriname', 'Vatican City', 'MS Zaandam',
                                 'Papua New Guinea', 'Sao Tome and Principe', 'Mauritania',
                                 'Bhutan', 'British Virgin Islands', 'St. Barth',
                                 'Western Sahara', 'Caribbean Netherlands', 'Anguilla',
                                 'Saint Pierre Miquelon', 'Yemen',
                                 'China',
                                 ])
    args = parser.parse_args()

    print(total_recovered_ratio(args.country_name))
